### ISSUE TITLE
query/gallery vehicle id and cam id.

### ISSUE THREAD

**Issue by xueping187** [heshuting555/AICITY2020_DMT_VehicleReID#10]
Hi, I notice that there is no query and gallery ids in the data. In your code, the query vehicle ids are all '2' and cam ids are 1. I do not see how to evaluate models with these labels. Or do I miss something?

![image](https://user-images.githubusercontent.com/59298049/93012809-b616ad00-f5d5-11ea-8d2c-d3d368a20a65.png)

Thanks.

**Comment by xueping187** [comment]
I am working on the AIC2020 DATA.

**Comment by heshuting555** [comment]
Because it is a competition, there is no label for the test set. Therefore, we assume that PID = 2 and camid = 1 which are consistent with the training process dataset format.
Thank you.
