### ISSUE TITLE
Convert  resnet50_80.pth  to .onnx 

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [heshuting555/AICITY2020_DMT_VehicleReID#12]
Hi, I want to convert your pre trained model to .onnx and then try in another project. How I can convert .pth to .onnx? 

Thanks.

**Comment by ganler** [comment]
@MuhammadAsadJaved Hi, have you successfully run through the pre-trained models? I tried https://github.com/heshuting555/AICITY2020_DMT_VehicleReID/issues/13, but it didn't work... 

So is there any other model that can work?

**Comment by MuhammadAsadJaved** [comment]
Hi @ganler, Sorry I haven't tried to run the demo yet. I just check this repo and asked about conversion, Because my target is to use the .onnx model if it can not then I am not moving to the next step.

**Comment by heshuting555** [comment]
Sorry, we don't support the onnx model convert. You can move to https://github.com/JDAI-CV/fast-reid/tree/master/tools/deploy for details.
