### ISSUE TITLE
 No such file or directory: '/root/mmdetection/reid_train_htc.bbox.json'

### ISSUE THREAD

**Issue by hanlanqian** [heshuting555/AICITY2020_DMT_VehicleReID#17]
Sorry to bother you. Where can i get the bboxes ?

**Comment by heshuting555** [comment]
Hi,
you can go to folder crop_dataset_generate https://github.com/heshuting555/AICITY2020_DMT_VehicleReID/tree/master/crop_dataset_generate for help.

using command `bash run.sh`

**Comment by hanlanqian** [comment]
感谢解答，但是我这个问题就是在运行run.sh时报错的，请问这个文件具体在哪里生成的呢( -'`-)

**Comment by heshuting555** [comment]
Hi～
run.sh 里面是一连串的命令，
应该是前面的命令没有成功运行才有了这个出错信息。
tools/test-generate.py 生成测试图片的信息
python tools/test.py 正常检测的操作，得到检测的框，结果将写入'/root/mmdetection/reid_train_htc.bbox.json'
应该是路径错了导致第一步可能就报错了。

**Comment by hanlanqian** [comment]
在tools/test.py中`checkpoint = load_checkpoint(model, args.checkpoint, map_location='cpu')`会报错`OSError: checkpoints/htc_dconv_c3-c5_mstrain_400_1400_x101_64x4d_fpn_20e_20190408-0e50669c.pth is not a checkpoint file`将相对路经换成绝对路径就没有问题了,是因为这个问题吗
