### ISSUE TITLE
I try to use arcface Loss, however the loss is much higher(about 2x at the beginning), and acc is 0 for a long time(never met before). Is it normal?

### ISSUE THREAD

**Issue by clw5180** [heshuting555/AICITY2020_DMT_VehicleReID#3]
RT, thanks.  I just set _C.MODEL.COS_LAYER = True

**Comment by heshuting555** [comment]
Yes，Arcface is more difficult to converge than CE loss, but it will not last too long. Generally, after three or four epoch, acc is not 0.
