### ISSUE TITLE
What is the main difference between this project and michuanhaohao's reid-strong-baseline? (except the new ideas in paper)

### ISSUE THREAD

**Issue by clw5180** [heshuting555/AICITY2020_DMT_VehicleReID#4]
I tried this project under same dataset and config file, but this project's mAP and R1 is about 1% lower than the origin baseline. Will it be affected by the ignite lib ?  Thanks !

**Comment by heshuting555** [comment]
This repo uses the origin baseline as a starting point, focusing on finding the strong baseline of vehicle reid and the baseline of the AICITY challenge.
