### ISSUE TITLE
train VeRi dataset 

### ISSUE THREAD

**Issue by chenxyyy** [heshuting555/AICITY2020_DMT_VehicleReID#5]
Hi @heshuting555 ！ thanks for your great work!

When I try to train the VeRi-776 dataset, I met a error.

`python train.py --config_file='configs/baseline_veri_r50_a.yml' MODEL.DEVICE_ID "('3')" OUTPUT_DIR "('log/')"` 

the following is the result

```
Traceback (most recent call last):
  File "train.py", line 62, in <module>
    model = make_model(cfg, num_class=num_classes)
  File "/data/DMT/model/make_model.py", line 126, in make_model
    model = Backbone(num_class, cfg)
  File "/data/DMT/model/make_model.py", line 67, in __init__
    self.base.load_param(model_path)
  File "/data/DMT/model/backbones/resnet_ibn_a.py", line 164, in load_param
    self.state_dict()[i.replace('module.','')].copy_(param_dict[i])
KeyError: 'base.conv1.weight'
```

I used your  weights  `resnet50_ibn_a_80.pth`

Could you please help me? Thank you very much!

**Comment by heshuting555** [comment]
Hi,

I guess you set cfg.MODEL.PRETRAIN_CHOICE==“self”. You can set cfg.MODEL.PRETRAIN_CHOICE == 'finetune'. And I specified a fixed num_class on line 57 of train.py, because it is convenient to reproduce the competition result. You can change it to `model = make_model (cfg, num_class = num_classes)` . And anything will go well.

Thank you for your attention！

**Comment by chenxyyy** [comment]
Thank you！

I have solved this problem according to your guidance！Thank you very much！

**Comment by SimonsXuan** [comment]
Hi, shuting! @heshuting555 I want to know have you use re-ranking to get  the three results of veri776?

**Comment by heshuting555** [comment]
Hi,
No, We did not use any post-processing methods. More specific details can be found in the log of our experiment.
Thank you for your attention！
