### ISSUE TITLE
VeRi Dataset

### ISSUE THREAD

**Issue by xflv** [heshuting555/AICITY2020_DMT_VehicleReID#6]
I want to test this baseline on the VeRi-776.First I modified the '.yml' to my own path, then I modified 'veri.py',the root was modified to my own path 'root = "/home/zhang/D/LXF/AICITY2020_DMT_VehicleReID/data' in '__init__',then I run 'python train.py --config_file='configs/baseline_veri_r50.yml'   . the code reports a error "RuntimeError: '../data/VeRi' is not available
'"  I ensure my path is right,and the dataset veri is available.why ? thank you 

![image](https://user-images.githubusercontent.com/55775284/83089799-d0318b80-a0c9-11ea-938d-6c17ecb8bb09.png)

![image](https://user-images.githubusercontent.com/55775284/83090075-6bc2fc00-a0ca-11ea-9005-852a340a2a09.png)

**Comment by heshuting555** [comment]
Hi,
The error message is `../data`, the previous directory.
Thanks for attention!

**Comment by xflv** [comment]
veri776,resnet50,其他的没改,怎么训练都是mAP 69%左右

**Comment by heshuting555** [comment]
Thank you for your attention. Can you share me with your training log. And then I may find where is going wrong.

Thanks
