### ISSUE TITLE
多模型叠加

### ISSUE THREAD

**Issue by HanwenCao** [heshuting555/AICITY2020_DMT_VehicleReID#8]
python train.py --config_file='configs/baseline_aic.yml' OUTPUT_DIR "('/data/model/0402_5/')" ### here we get the model resnet101_ibn_a_80.pth in the 0402_5.  这个模型似乎训练后没有用到吗？

**Comment by HanwenCao** [comment]
python train.py --config_file='configs/baseline_aic.yml' INPUT.SIZE_TRAIN "([384,384])" INPUT.SIZE_TEST "([384,384])" DATALOADER.NUM_INSTANCE "(6)" SOLVER.IMS_PER_BATCH "(60)" OUTPUT_DIR "('/data/model/0409_2/')"  ### here we get the model resnet101_ibn_a_80.pth in the 0409_2.
请问这个模型的训练，与之前很类似，是什么作用？谢谢指教

**Comment by heshuting555** [comment]
You can see these models appear in ensemble_dist.py. It is used for model fusion to increase the diversity of models.

Thanks for your attention.
